# Generated by Django 4.2.8 on 2024-02-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_category', '0006_alter_postcategory_name'),
        ('posts', '0002_delete_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_category.postcategory'),
            preserve_default=False,
        ),
    ]
