# Generated by Django 4.2.8 on 2024-02-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
